Candidate/urls.py
from django.urls import path
from . import views

app_name = 'Candidate'
urlpatterns = [
    path('', views.home, name='home'),
    path('choicefilling/', views.ChoiceFilling, name="choicefilling"),
    path('user_login/', views.user_login, name='user_login'),
    path('change_password/', views.change_password, name='change_password'),
    path('register/', views.register, name='register'),

]

JeeSeatAllocation/urls.py
from django.contrib import admin
from django.urls import path, include
from Candidate import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('Candidate.urls', namespace="Candidate")),
    path('', views.home, name='home'),
    path('logout/', views.user_logout, name='logout'),
    path('assign/', views.assign, name='assign'),
    path('tozero/', views.brnull, name='tozero'),
    path('assign-admin/', views.admin_home, name='admin_home'),
    path('tofreeze/', views.to_freeze, name='tofreeze'),
    path('toslide/', views.to_slide, name='toslide'),
    path('toremove/', views.to_remove, name='toremove'),
]

Candidate/models.py
from django.db import models
from phone_field import PhoneField
from django.contrib.auth.models import User

# Create your models here.
CHOICES = (
    ("GEN", "GEN"),
    ("OBC", "OBC"),
    ("SC", "SC"),
    ("ST", "ST"),
    ("GENPWD", "GENPWD"),
    ("OBCPWD", "OBCPWD"),
    ("SCPWD", "SCPWD"),
    ("STPWD", "STPWD"),
)

CHOICES1 = (
    ("MALE", "MALE"),
    ("FEMALE", "FEMALE"),
    ("OTHER", "OTHER"),
)


class College(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name


class Branch(models.Model):
    name = models.CharField(max_length=100, null=False)
    college = models.ForeignKey(College, on_delete=models.CASCADE, null=False)
    capacity = models.IntegerField(default=50)
    preferences = models.CharField(max_length=1000, default="", null=True, blank=True)
    gen_capacity = models.IntegerField(default=0)
    gen_pwd_capacity = models.IntegerField(default=0)
    obc_ncl_capacity = models.IntegerField(default=0)
    obc_ncl_pwd_capacity = models.IntegerField(default=0)
    sc_capacity = models.IntegerField(default=0)
    sc_pwd_capacity = models.IntegerField(default=0)
    st_capacity = models.IntegerField(default=0)
    st_pwd_capacity = models.IntegerField(default=0)
    gen_capacity_filled = models.IntegerField(default=0)
    gen_pwd_capacity_filled = models.IntegerField(default=0)
    obc_ncl_capacity_filled = models.IntegerField(default=0)
    obc_ncl_pwd_capacity_filled = models.IntegerField(default=0)
    sc_capacity_filled = models.IntegerField(default=0)
    sc_pwd_capacity_filled = models.IntegerField(default=0)
    st_capacity_filled = models.IntegerField(default=0)
    st_pwd_capacity_filled = models.IntegerField(default=0)

    def setpreferences(self, x):
        self.preferences = ",".join(x)

    def getpreferences(self):
        return self.preferences.split(',')

    def __str__(self):
        return self.college.name + "-" + self.name


class Candidate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rollnumber = models.CharField(max_length=15, null=False, unique=True)
    category = models.CharField(max_length=100, choices=CHOICES, null=False)
    gender = models.CharField(max_length=100, choices=CHOICES1, null=False)
    rank = models.IntegerField(null=False, unique=True)
    birthdate = models.DateField(null=True, blank=True)
    email = models.EmailField(null=False)
    phone = PhoneField(null=False, blank=True)
    preferences = models.CharField(max_length=1000, default="", null=True, blank=True)
    freeze = models.IntegerField(default=0)
    locked = models.IntegerField(default=0)
    removed = models.IntegerField(default=0)
    is_admin = models.IntegerField(default=0)
    final_seat = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True, blank=True)
    quota_for_seat = models.CharField(max_length=100, choices=CHOICES, blank=True)

    def setpreferences(self, x):
        self.preferences = ",".join(x)

    def getpreferences(self):
        return self.preferences.split(',')

    class Meta:
        ordering = ['rank']

    def __str__(self):
        return self.rollnumber

Candidate/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class StudentUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ('rollnumber', 'category', 'birthdate', 'phone', 'rank', 'gender', 'email')


class FreezeForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ('rollnumber', 'rank')

Candidate/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from django.contrib import messages
from Candidate.forms import StudentUserForm, CandidateForm, FreezeForm


# Create your views here.


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def home(request):
    if request.user.is_authenticated:
        dict1 = Candidate.objects.filter(user=request.user)

        if len(dict1) > 0:
            if dict1[0].is_admin == 1 :
                return render(request,'Candidate/admin.html')
            else:
                freeze_form = FreezeForm()
                if dict1[0].freeze == 1:
                    return render(request, 'Candidate/freezed.html', {'seat': dict1[0].final_seat})
                else:
                    return render(request, 'Candidate/base.html', {'seat': dict1[0].final_seat, 'freeze': freeze_form})
        else:
            return render(request, 'Candidate/removed.html')
    else:
        # not logged in
        return render(request, 'Candidate/base.html')


def admin_home(request):
    if request.user.is_authenticated:
        dict1 = Candidate.objects.filter(user=request.user)
        if len(dict1) > 0:
            return render(request, 'Candidate/admin.html')
        else:
            return render(request, 'Candidate/admin.html')
    else:
        # not logged in
        return render(request, 'Candidate/base.html')


def register(request):
    registered = False
    if request.method == "POST":
        print("hahaha")
        user_form = StudentUserForm(data=request.POST)
        info_form = CandidateForm(data=request.POST)
        if user_form.is_valid() and info_form.is_valid():
            print("lalala")
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = info_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            if user:
                print("papapa")
                if user.is_active:
                    print("oaoaoa")
                    login(request, user)
                    return HttpResponseRedirect(reverse('home'))

                else:
                    return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponseRedirect(reverse('home'))
    else:
        user_form = StudentUserForm()
        info_form = CandidateForm()
    return render(request, 'Candidate/register_page.html',
                  {'user_form': user_form, 'info_form': info_form, 'registered': registered, 'registerFlag': 0})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                # to check the type of user to log in

                dict1 = Candidate.objects.filter(user=request.user)

                if len(dict1) > 0:
                    if dict1[0].is_admin == 1:
                        return HttpResponseRedirect(reverse('admin_home'))
                    else:
                        return HttpResponseRedirect(reverse('home'))
                else:
                    return HttpResponseRedirect(reverse('home'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print("someone tried to login and failed")
            print("Username: {} Password: {}".format(username, password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'Candidate/base.html', {})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect(reverse('home'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'Candidate/change_password.html', {
        'form': form
    })


def ChoiceFilling(request):
    if request.POST:
        print(request.POST)
        cand = Candidate.objects.get(user=request.user)
        if(cand.locked == 0):
            lock = 0
            if "ADD" in request.POST and "choice" in request.POST:
                arr = []
                branchprefdone = []
                branches = Branch.objects.all()
                pref = cand.preferences
                ask = ""
                if pref is ask:
                    cand.preferences = str(request.POST['choice'])
                else:
                    cand.preferences = str(cand.preferences) + "," + str(request.POST['choice'])
                cand.save()
                pref = cand.preferences
                if pref:
                    arr = pref.split(",")
                    for x in arr:
                        temp = x.split('-')
                        if len(temp) == 2:
                            branchprefdone.append(
                                Branch.objects.get(name=temp[1], college=College.objects.get(name=temp[0])))
                #     branchprefdone = Branch.objects.filter(name__in=brname,college_name__in=coll)
                branchrem = []
                for x in branches:
                    if x not in branchprefdone:
                        branchrem.append(x)
            elif "REMOVE" in request.POST and "Rchoice" in request.POST:
                print(len(request.POST['Rchoice']))
                print("-----------=-=-----------=-=-=--==-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-==-==-=-=-=-=--=-=-=-")
                arr = []
                branchprefdone = []
                branches = Branch.objects.all()
                cand = Candidate.objects.get(user=request.user)
                pref = cand.preferences
                temppref = ""
                if pref is not None:
                    arr = pref.split(",")
                    for x in arr:
                        if x in request.POST['Rchoice']:
                            pass
                        elif temppref == "":
                            temppref = x
                        else:
                            print(x)
                            temppref = temppref + ',' + x
                cand.preferences = temppref
                cand.save()
                pref = temppref
                if pref:
                    arr1 = pref.split(",")
                    for x in arr1:
                        temp = x.split('-')
                        if len(temp) == 2:
                            branchprefdone.append(
                                Branch.objects.get(name=temp[1], college=College.objects.get(name=temp[0])))
                #     branchprefdone = Branch.objects.filter(name__in=brname,college_name__in=coll)
                branchrem = []
                for x in branches:
                    if x not in branchprefdone:
                        branchrem.append(x)

            else:
                arr = []
                branchprefdone = []
                branches = Branch.objects.all()
                cand = Candidate.objects.get(user=request.user)
                pref = cand.preferences
                if pref:
                    arr = pref.split(",")
                    for x in arr:
                        temp = x.split('-')
                        if len(temp) == 2:
                            branchprefdone.append(
                                Branch.objects.get(name=temp[1], college=College.objects.get(name=temp[0])))
                branchrem = []
                for x in branches:
                    if x not in branchprefdone:
                        branchrem.append(x)
        else:
            lock = 1;
            arr = []
            branchprefdone = []
            branches = Branch.objects.all()
            cand = Candidate.objects.get(user=request.user)
            pref = cand.preferences
            if pref:
                arr = pref.split(",")
                coll = []
                brname = []
                temp = []
                for x in arr:
                    temp = x.split('-')
                    if len(temp) == 2:
                        branchprefdone.append(Branch.objects.get(name=temp[1], college=College.objects.get(name=temp[0])))
            branchrem = []
            for x in branches:
                if x not in branchprefdone:
                    branchrem.append(x)
    else:
        arr = []
        branchprefdone = []
        branches = Branch.objects.all()
        cand = Candidate.objects.get(user=request.user)
        lock = cand.locked
        pref = cand.preferences
        if pref:
            arr = pref.split(",")
            coll = []
            brname = []
            temp = []
            for x in arr:
                temp = x.split('-')
                if len(temp) == 2:
                    branchprefdone.append(Branch.objects.get(name=temp[1], college=College.objects.get(name=temp[0])))
        branchrem = []
        for x in branches:
            if x not in branchprefdone:
                branchrem.append(x)

    return render(request, 'Candidate/choicefilling.html',
                  {'branches': branches, 'branchprefdone': branchprefdone, 'branchrem': branchrem, 'lock':lock})


def brnull(request):

templates/candidate/admin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block js %}
    {% endblock %}
  </head>
  <body>

    {% if user.is_authenticated %}

    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'admin_home' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>

        </ul>
      </div>

    </nav>

    <div class="container">
      <h4 class="text-center text-danger">HELLO {{user.username}}</h4>
      <br>
      <div class="jumbotron" style="background-color: lightgreen;" >
      <h3>
        1st Round:
      </h3>
      <div>
          <h4>
            1.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            2. <a href="{% url 'assign' %}"> to assign seats 1st time</a>
          </h4>
        </div>

      <h3>
        2nd Round:
      </h3>
      <div>
          <h4>
            1. First remove some users and freeze for some other users
            <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 2nd time</a>
          </h4>
        </div>

      <h3>
        3rd Round:
      </h3>
      <div>
          <h4>
            1. First remove some users and freeze for some other users
            <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 3rd time</a>
          </h4>
        </div>
      <h3>
        4th Round:
      </h3>
      <div>
          <h4>
             1. First remove some users and freeze for some other users
             <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 4th time</a>
          </h4>
        </div>

      <h3>
        5th Round:
      </h3>
      <div>
          <h4>
            1. First remove some users and freeze for some other users
            <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 5th time</a>
          </h4>
        </div>

      <h3>
        6th Round:
      </h3>
      <div>
          <h4>
            1. First remove some users and freeze for some other users
            <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 6th time</a>
          </h4>
        </div>
        <h3>
        7th Round:
      </h3>
      <div>
          <h4>
            1. First remove some users and freeze for some other users
            <br>
            2.<a href="{% url 'tozero' %}"> To initialise </a>
            <br>
            3. <a href="{% url 'assign' %}"> to assign seats 7th time</a>
          </h4>
        </div>
      {% block body_block %}



      {% endblock %}

    </div>


    {% else %}

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4>Please Log In</h4>

          <form action={% url 'Candidate:user_login' %} method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Username">
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" placeholder="Password">
            <br>
            <input type="submit" class="btn  btn-danger" name="" value="Login">
          </form>

        </div>

      </div>

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4 class="text-danger">Haven't Registered, Register!</h4>

          <a href={% url 'Candidate:register' %} class="text-danger"><button type=submit class="btn btn-primary">REGISTER</button></a>
        </div>
</div>
      </div>


    {% endif %}


  </body>
</html>

templates/candidate/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block js %}
    {% endblock %}
  </head>
  <body>

    {% if user.is_authenticated %}

    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'home' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'Candidate:choicefilling' %}">Choice_Filling</a></li>
          <li><a class="navbar-link" href="{% url 'Candidate:change_password' %}">Change Password</a></li>
          <li><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>

        </ul>
      </div>

    </nav>

    <div class="container">
      <h4 class="text-center text-danger">HELLO {{user.username}}</h4>

      <h3>
        Your Final Seat as of now is {{seat}}
      </h3>


          <br>
      {% block body_block %}

<br>
      <br>
      <h4>
        To freeze your seat, submit the following form.
      </h4>
      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">
<form action="{% url 'tofreeze' %}" method="post">
            {% csrf_token %}
            {{ freeze.as_p }}
            <input type="submit" class="btn btn-primary" name="" value="FREEZE">
      </form>
</div>
</div>
<h4>
        To Float your seat, submit the following form.
      </h4>
      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">
<form action="{% url 'tofreeze' %}" method="post">
            {% csrf_token %}
            {{ freeze.as_p }}
            <input type="submit" class="btn btn-primary" name="" value="FLOAT">
      </form>
</div>
</div>
<h4>
        To Slide your seat, submit the following form.
      </h4>
      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">
<form action="{% url 'toslide' %}" method="post">
            {% csrf_token %}
            {{ freeze.as_p }}
            <input type="submit" class="btn btn-primary" name="" value="SLIDE">
      </form>
</div>
</div>

        <h4>
        To Quit the counselling, submit the following form.
      </h4>
      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">
<form action="{% url 'toremove' %}" method="post">
            {% csrf_token %}
            {{ freeze.as_p }}
            <input type="submit" class="btn btn-primary" name="" value="REMOVE">
      </form>
</div>
</div>

      {% endblock %}

    </div>


    {% else %}
      <br>
      <br>

      <div class="container mt-5">
        <h2 class="text-center text-danger">JEE SEAT ALLOCATION</h2>
        <br>
        <br>
          <div style="background-color:#b0e0e6" class="jumbotron text-center">



          <form action={% url 'Candidate:user_login' %} method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Username">
            <br>
            <br>

            <label for="password">Password</label>
            <input type="password" name="password" placeholder="Password">
            <br>
            <br>

            <input type="submit" class="btn  btn-danger" name="" value="Login">
          </form>

        </div>

      </div>

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron text-center">

          <h4 class="text-danger">Haven't Registered, Register!</h4>

          <a href={% url 'Candidate:register' %} class="text-danger"><button type=submit class="btn btn-primary">REGISTER</button></a>
        </div>

      </div>


    {% endif %}


  </body>
</html>

templates/candidate/change_password.html
{% extends 'Candidate/base.html' %}
{% block body_block %}
 <div class="container">
      <div style="background-color:#b0e0e6" class="jumbotron">
		<form method="post">
	  		{% csrf_token %}
	  		{{ form }}
	  		<button type="submit" class="btn btn-primary">Save changes</button>
		</form>
	</div>
 </div>
{% endblock %}

templates/candidate/freezed.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block js %}
    {% endblock %}
  </head>
  <body>

    {% if user.is_authenticated %}

    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'home' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'Candidate:choicefilling' %}">Choice_Filling</a></li>
          <li><a class="navbar-link" href="{% url 'Candidate:change_password' %}">Change Password</a></li>
          <li><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>

        </ul>
      </div>

    </nav>

    <div class="container">
      <h4 class="text-center text-danger">HELLO {{user.username}}</h4>

      <h3>
        Your Final Seat as of now is {{seat}}
      </h3>


          <br>
      {% block body_block %}
            <h3>
                YOUR SEAT HAS BEEN FREEZED
            </h3>
      {% endblock %}

    </div>


    {% else %}

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4>Please Log In</h4>

          <form action={% url 'Candidate:user_login' %} method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Username">
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" placeholder="Password">
            <br>
            <input type="submit" class="btn  btn-danger" name="" value="Login">
          </form>

        </div>

      </div>

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4 class="text-danger">Haven't Registered, Register!</h4>

          <a href={% url 'Candidate:register' %} class="text-danger"><button type=submit class="btn btn-primary">REGISTER</button></a>
        </div>

      </div>


    {% endif %}


  </body>
</html>

templates/candidate/register_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
	<br>
	<br><br>
<div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4 class="text-danger">ENTER YOUR DETAILS HERE...</h4>
<form action="{% url 'Candidate:register' %}" method="post">     
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ info_form.as_p }}
            <input type="submit" class="btn btn-primary" name="" value="Register">
</form>

</div>
</div>
</body>
</html>

templates/candidate/removed.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {% block js %}
    {% endblock %}
  </head>
  <body>

    {% if user.is_authenticated %}

    <nav class="navbar navbar-default navbar-static-top">

      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'home' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'logout' %}">Log Out</a></li>

        </ul>
      </div>

    </nav>

    <div class="container">
      <h4 class="text-center text-danger">HELLO {{user.username}}</h4>

      <h4>
          Your seat has been removed.
      </h4>

          <br>
      {% block body_block %}



      {% endblock %}

    </div>


    {% else %}

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4>Please Log In</h4>

          <form action={% url 'Candidate:user_login' %} method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Username">
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" placeholder="Password">
            <br>
            <input type="submit" class="btn  btn-danger" name="" value="Login">
          </form>

        </div>

      </div>

      <div class="container">
        <div style="background-color:#b0e0e6" class="jumbotron">

          <h4 class="text-danger">Haven't Registered, Register!</h4>

          <a href={% url 'Candidate:register' %} class="text-danger"><button type=submit class="btn btn-primary">REGISTER</button></a>
        </div>

      </div>


    {% endif %}


  </body>
</html>